version: '3.1'

services:

  app:
    build:
      ./
    environment:
      DATABASE_URL: postgres://gandalf:mellon@localhost/pom
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gandalf
      POSTGRES_PASSWORD: mellon
      POSTGRES_DB: pom