version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gandalf
      POSTGRES_PASSWORD: mellon
      POSTGRES_DB: pom